spring:
  security:
    user:
      name: admin@example.com  # Временный админ (можно удалить после настройки)
      password: admin123
      roles: ADMIN
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true


jwt:
  secret: "+XTu1xFeVLLxmyC/oIeabsljz28rWnsmIFLBLhctiQw=" # Сгенерировать: openssl rand -base64 32
  Ïexpiration-ms: 86400000 # 24 часа

telegram:
  token: ${TELEGRAM_TOKEN}
  chat_id: ${TELEGRAM_CHAT_ID}